map_type: costmap

obstacle_range: 5.0
raytrace_range: 8.0

transform_tolerance: 0.2

#robot_radius: ir_of_robot 
inflation_radius: 0.45

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /sweeping_bot/laser/scan, marking: true, clearing: true}
